## Numpy Array Operations

### Indexing and Slicing

In [1]:
import numpy as np

- **Indexing and Slicing 1D Array**

In [2]:
arr = np.arange(1,11)
print(f"Orignal Array: {arr}")

print(f"\nIndexing any number: {arr[5]}")

print(f"\nNegative indexing: {arr[-3]}")

print(f"\nSlicing: {arr[3:6]}")

print(f"\nSlicing with step: {arr[1:9:2]}")

print(f"\nNegative Slicing: {arr[-5:-2]}")

Orignal Array: [ 1  2  3  4  5  6  7  8  9 10]

Indexing any number: 6

Negative indexing: 8

Slicing: [4 5 6]

Slicing with step: [2 4 6 8]

Negative Slicing: [6 7 8]


- **Indexing and Slicing 2D Array**

In [3]:
arr_2D = np.array([ [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9] ])

print(f"Original 2D Array:\n{arr_2D}")

# targeting an element on specific row and column
print(f"\nSpecific element: {arr_2D[2,2]}")         # 3rd row 3rd column

# targeting entire row
print(f"\nEntire row: {arr_2D[1]}")                 # entire 2nd row

# targeting entire column
print(f"\nEntire column: {arr_2D[:,0]}")            # entire 1st column

Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Specific element: 9

Entire row: [4 5 6]

Entire column: [1 4 7]


### Sorting arrays

In [ ]:
arr_1D_unsorted = np.array([3, 5, 2, 5, 1, 8, 0, 4, 2, 9, 6])
print(f"Unsorted 1D array: {arr_1D_unsorted}")

print(f"\nSorted 1D array: {np.sort(arr_1D_unsorted)}")

arr_2D_unsorted = np.array([ [3, 1],
                             [1, 2],
                             [2, 3] ])

print(f"\nUnsorted 2D array: \n{arr_2D_unsorted}")

print(f"\nSorted 2D array by column: \n{np.sort(arr_2D_unsorted, axis=0)}") # axis = 0 for column-wise sorting
print(f"\nSorted 2D array by row: \n{np.sort(arr_2D_unsorted, axis=1)}")    # axis = 1 for row-wise sorting

Unsorted 1D array: [3 5 2 5 1 8 0 4 2 9 6]

Sorted 1D array: [0 1 2 2 3 4 5 5 6 8 9]

Unsorted 2D array: 
[[3 1]
 [1 2]
 [2 3]]

Sorted 2D array by column: 
[[1 1]
 [2 2]
 [3 3]]

Sorted 2D array by row: 
[[1 3]
 [1 2]
 [2 3]]


### Filtering Arrays

In [5]:
numbers = np.arange(1,11)
print(f"Original Array: {numbers}")

even = numbers[numbers % 2 == 0]
print(f"\nEven Numbers: {even}")

Original Array: [ 1  2  3  4  5  6  7  8  9 10]

Even Numbers: [ 2  4  6  8 10]


- **Filtering using Mask:** Masking means using a condition to find and select specific values from an array.

For Example:
`numbers[numbers % 2 != 0]`, we store it in a variable `(mask_odd)` and then use it — e.g., `numbers[mask_odd]`.

In [6]:
mask_odd = numbers % 2 != 0
print(f"Odd Numbers: {numbers[mask_odd]}")

mask = numbers > 5
print(f"\nNumbers greater than 5: {numbers[mask]}")

Odd Numbers: [1 3 5 7 9]

Numbers greater than 5: [ 6  7  8  9 10]


### `np.where()` method in Numpy Arrays

In [18]:
indices = [2, 4, 6]
print(numbers[indices])

where_result = np.where(numbers > 4)    # it is also masking, here we are using '.where()' method 
print(numbers[where_result])


[3 5 7]
[ 5  6  7  8  9 10]


The `np.where()` function is used to apply a condition to each element of an array.  
It returns one value **for that element** if the condition is true,  
and another value **for that same element** if the condition is false.

**Syntax:**
```python
np.where(condition, value_if_true, value_if_false)

In [19]:
# first it will check the condition on each element of the array, then will apply given operation to only those elements which fulfills the condition, and another value for those elements which don't fulfill the condition.

condition_array = np.where(numbers > 5, numbers * 3, numbers)
print(condition_array)

new_num = np.where(numbers > 3, numbers * 4, numbers * 2)
print(new_num)

[ 1  2  3  4  5 18 21 24 27 30]
[ 2  4  6 16 20 24 28 32 36 40]


### Some more manipulations in np arrays

- **Concatenating array:** Concatenating arrays using `np.concatenate()` method

In [9]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
arr_3 = np.array([7, 8, 9])

print(f"This one is adding array: {arr_1 + arr_2 + arr_3}") # this is not concatenating, its adding the values

print(f"Concatenating arrays: {np.concatenate((arr_1, arr_2, arr_3))}")

This one is adding array: [12 15 18]
Concatenating arrays: [1 2 3 4 5 6 7 8 9]


- **Checking array compatibility:** Checking whether the arrays have same shapes using `.shape` method.

In [10]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a3 = np.array([7, 8, 9])

# all the arrays have same shape i.e. 1x3
print(f"Array 1, 2 and 3 are compatible: {a1.shape == a2.shape == a3.shape}")

Array 1, 2 and 3 are compatible: True


- **Adding a rows and columns in existing array:**

`vstack` is used to add data vertically (row-wise)

`hstack` is used to add data horizontally (column-wise)

In [11]:
original_array = np.array([ [1, 3],
                            [5, 7] ])
new_row = np.array([[4, 6]])    #should create the new row in 2D. though numpy adjust it automatically.
array_with_row = np.vstack((original_array, new_row))

print(f"Original array:\n{original_array}")
print(f"Array with new row:\n{array_with_row}")
new_row = np.array([[4, 6]])


new_col = np.array([[2], [0]])    #should create the new col in 2D. though numpy adjust it automatically.
array_with_col = np.hstack((original_array, new_col))

print(f"Original array:\n{original_array}")
print(f"Array with new column:\n{array_with_col}")
new_row = np.array([[4, 6]])

Original array:
[[1 3]
 [5 7]]
Array with new row:
[[1 3]
 [5 7]
 [4 6]]
Original array:
[[1 3]
 [5 7]]
Array with new column:
[[1 3 2]
 [5 7 0]]


- **Deleting data:** Deleting data from np array

np.delete(array, index_or_indices, axis=None)

`None` → flattens the array and deletes from the flat version

`0` → delete rows

`1` → delete columns

If you don’t pass axis, NumPy will flatten the array and delete based on 1D indexing — which usually leads to confusing results in 2D arrays.

In [12]:
# deleting from 1D array

array = np.array([1, 2, 3, 4, 5])
deleted = np.delete(array, 2)

print(f"Original Array: \n{array}")
print(f"\nArray after deletion: \n{deleted}")

# deleting from 2D array

array = np.array([ [1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9] ])
delete_row = np.delete(array, 1, axis=0)

print(f"\nOriginal Array: \n{array}")
print(f"\nArray after row deletion: \n{delete_row}")

delete_col = np.delete(array, 1, axis=1)

print(f"\nOriginal Array: \n{array}")
print(f"\nArray after column deletion: \n{delete_col}")


Original Array: 
[1 2 3 4 5]

Array after deletion: 
[1 2 4 5]

Original Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after row deletion: 
[[1 2 3]
 [7 8 9]]

Original Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after column deletion: 
[[1 3]
 [4 6]
 [7 9]]


- **Deleting a single element from a 2D array:**

You cannot directly delete a single element from a row or column of a 2D array in place, because NumPy arrays must remain rectangular (all rows same length).

For that, you have to `flatten` the array and then delete the element and then convert the array to 2D (if needed).


In [13]:
dummy_array = np.array([ [1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9] ])

# suppose you want to delete element 8, that is 7th in index
flatten_index = 7

element_deletion = np.delete(dummy_array, flatten_index) # deleted the element but now the array is in 1D.
array_in_2D = np.resize(element_deletion, (3,3))    # resizing the array to make 2D again (optional)

print(f"Original Array: \n{dummy_array}")
print(f"\nArray after deleting a single element: \n{element_deletion}")
print(f"\nArray again in 2D (optional): \n{array_in_2D}")

Original Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after deleting a single element: 
[1 2 3 4 5 6 7 9]

Array again in 2D (optional): 
[[1 2 3]
 [4 5 6]
 [7 9 1]]
