## Numpy Array Operations

### Indexing and Slicing

In [2]:
import numpy as np

- **Indexing and Slicing 1D Array**

In [3]:
arr = np.arange(1,11)
print(f"Orignal Array: {arr}")

print(f"\nIndexing any number: {arr[5]}")

print(f"\nNegative indexing: {arr[-3]}")

print(f"\nSlicing: {arr[3:6]}")

print(f"\nSlicing with step: {arr[1:9:2]}")

print(f"\nNegative Slicing: {arr[-5:-2]}")

Orignal Array: [ 1  2  3  4  5  6  7  8  9 10]

Indexing any number: 6

Negative indexing: 8

Slicing: [4 5 6]

Slicing with step: [2 4 6 8]

Negative Slicing: [6 7 8]


- **Indexing and Slicing 2D Array**

In [4]:
arr_2D = np.array([ [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9] ])

print(f"Original 2D Array:\n{arr_2D}")

# targeting an element on specific row and column
print(f"\nSpecific element: {arr_2D[2,2]}")         # 3rd row 3rd column

# targeting entire row
print(f"\nEntire row: {arr_2D[1]}")                 # entire 2nd row

# targeting entire column
print(f"\nEntire column: {arr_2D[:,0]}")            # entire 1st column

Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Specific element: 9

Entire row: [4 5 6]

Entire column: [1 4 7]


### Sorting arrays

In [5]:
arr_1D_unsorted = np.array([3, 5, 2, 5, 1, 8, 0, 4, 2, 9, 6])
print(f"Unsorted 1D array: {arr_1D_unsorted}")

print(f"\nSorted 1D array: {np.sort(arr_1D_unsorted)}")

arr_2D_unsorted = np.array([ [3, 1],
                             [1, 2],
                             [2, 3] ])

print(f"\nUnsorted 2D array: \n{arr_2D_unsorted}")

print(f"\nSorted 2D array by column: \n{np.sort(arr_2D_unsorted, axis=0)}") # axis = 0 for column-wise sorting
print(f"\nSorted 2D array by row: \n{np.sort(arr_2D_unsorted, axis=1)}")    # axis = 0 for row-wisbe sorting

Unsorted 1D array: [3 5 2 5 1 8 0 4 2 9 6]

Sorted 1D array: [0 1 2 2 3 4 5 5 6 8 9]

Unsorted 2D array: 
[[3 1]
 [1 2]
 [2 3]]

Sorted 2D array by column: 
[[1 1]
 [2 2]
 [3 3]]

Sorted 2D array by row: 
[[1 3]
 [1 2]
 [2 3]]


### Filtering Arrays

In [6]:
numbers = np.arange(1,11)
print(f"Original Array: {numbers}")

even = numbers[numbers % 2 == 0]
print(f"\nEven Numbers: {even}")

Original Array: [ 1  2  3  4  5  6  7  8  9 10]

Even Numbers: [ 2  4  6  8 10]


- **Filtering using Mask:** Masking means using a condition to find and select specific values from an array.

For Example:
`numbers[numbers % 2 != 0]`, we store it in a variable `(mask_odd)` and then use it — e.g., `numbers[mask_odd]`.

In [7]:
mask_odd = numbers % 2 != 0
print(f"Odd Numbers: {numbers[mask_odd]}")

mask = numbers > 5
print(f"\nNumbers greater than 5: {numbers[mask]}")

Odd Numbers: [1 3 5 7 9]

Numbers greater than 5: [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [10]:
indices = [2, 4, 6]
print(numbers[indices])

where_result = np.where(numbers > 4)    # it is also masking, here we are using '.where()' method 
print(numbers[where_result])

[3 5 7]
[ 5  6  7  8  9 10]


The `np.where()` function is used to apply a condition to each element of an array.  
It returns one value **for that element** if the condition is true,  
and another value **for that same element** if the condition is false.

**Syntax:**
```python
np.where(condition, value_if_true, value_if_false)

In [12]:
# first it will check the condition on each element of the array, then will apply given operation to only those elements which fulfills the condition, and another value for those elements which don't fulfill the condition.

condition_array = np.where(numbers > 5, numbers * 3, numbers)
print(condition_array)

[ 1  2  3  4  5 18 21 24 27 30]


### Adding or removing data

- **Concatenating array:** Concatenating arrays using `np.concatenate()` method

In [15]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
arr_3 = np.array([7, 8, 9])

print(f"This one is adding array: {arr_1 + arr_2 + arr_3}") # this is not concatenating, its adding the values

print(f"Concatenating arrays: {np.concatenate((arr_1, arr_2, arr_3))}")

This one is adding array: [12 15 18]
Concatenating arrays: [1 2 3 4 5 6 7 8 9]
