## Numpy Array Operations

In [1]:
import numpy as np

- **Indexing and Slicing 1D Array**

In [10]:
arr = np.arange(1,11)
print(f"Orignal Array: {arr}")

print(f"\nIndexing any number: {arr[5]}")

print(f"\nNegative indexing: {arr[-3]}")

print(f"\nSlicing: {arr[3:6]}")

print(f"\nSlicing with step: {arr[1:9:2]}")

print(f"\nNegative Slicing: {arr[-5:-2]}")

Orignal Array: [ 1  2  3  4  5  6  7  8  9 10]

Indexing any number: 6

Negative indexing: 8

Slicing: [4 5 6]

Slicing with step: [2 4 6 8]

Negative Slicing: [6 7 8]


- **Indexing and Slicing 2D Array**

In [19]:
arr_2D = np.array([ [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9] ])

print(f"Original 2D Array:\n{arr_2D}")

# targeting an element on specific row and column
print(f"\nSpecific element: {arr_2D[2,2]}")         # 3rd row 3rd column

# targeting entire row
print(f"\nEntire row: {arr_2D[1]}")                 # entire 2nd row

# targeting entire column
print(f"\nEntire column: {arr_2D[:,0]}")            # entire 1st column

Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Specific element: 9

Entire row: [4 5 6]

Entire column: [1 4 7]
