## Numpy Array and Basics
Learning about Numpy and its arrays

In [2]:
import numpy as np

In [3]:
import numpy as np

### Creating Arrays from List

In [5]:
array_1D = np.array([1, 2, 3, 4, 5]) # is .array function ko ek hi arguement chahiye hoti hai, jo hai ek list.
array_2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"1D array: {array_1D}")
print(f"2D array: {array_2D}")

1D array: [1 2 3 4 5]
2D array: [[1 2 3 4]
 [5 6 7 8]]


### List vs Numpy Array

In [ ]:
py_list = [1, 2, 3, 4, 5]
print(f"Python list multiplication: {py_list * 2}")

np_array = np.array([1, 2, 3, 4, 5])    # it multiplies the values inside (basically element wise) 
print(f"Python list multiplication: {np_array * 2}")

import time

start = time.time()

py_list = [i*2 for i in range(1000000)]
print(f"\nTime for list multiplication: {(time.time() - start):.5f}")

start = time.time()

np_array = np.arange(1000000) * 2
print(f"Time for numpy arrat multiplication: {(time.time() - start):.5f}")

Python list multiplication: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Python list multiplication: [ 2  4  6  8 10]
Time for list multiplication: 0.20456
Time for numpy arrat multiplication: 0.00763


### Creating Numpy arrays from scratch
We have some methods provided by numpy to create arrays/matrices

- np.zeros( (rows, column) ) ====>(this gives array of zeros)
- np.ones( (rows, column) )  ====>           (this gives array of ones)
- np.full( (rows, column), any num ) ====>   (this gives array of any number you provide in the arguements)
- np.random( (row, column) ) ====>   (gives array of random numbers)
- np.arange( (start, stop, step) ) ====>   (gives array of sequence)

In [14]:
zeros = np.zeros((3,4))
print(f"Zeros array (matrice): \n{zeros}")

ones = np.ones((3,4))
print(f"\nOnes array (matrice): \n{ones}")

full = np.full((3,3),8)
print(f"\nFULL array (matrice) of any given number: \n{full}")

random = np.random.random((4,3))
print(f"\nArray (matrice) of random numbers: \n{random}")

sequence = np.arange(0, 11, 2)
print(f"\nSequence array: \n{sequence}")


Zeros array (matrice): 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array (matrice): 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

FULL array (matrice) of any given number: 
[[8 8 8]
 [8 8 8]
 [8 8 8]]

Array (matrice) of random numbers: 
[[0.40752593 0.22664671 0.18820677]
 [0.10051367 0.64561645 0.00272414]
 [0.961337   0.36088348 0.19396148]
 [0.48882987 0.54831365 0.70106003]]

Sequence array: 
[ 0  2  4  6  8 10]
