## Numpy Array and Basics
Learning about Numpy and its arrays

In [1]:
import numpy as np

### Creating Arrays from List

In [2]:
array_1D = np.array([1, 2, 3, 4, 5]) # is .array function ko ek hi arguement chahiye hoti hai, jo hai ek list.
array_2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"1D array: {array_1D}")
print(f"2D array: {array_2D}")

1D array: [1 2 3 4 5]
2D array: [[1 2 3 4]
 [5 6 7 8]]


### List vs Numpy Array

In [3]:
py_list = [1, 2, 3, 4, 5]
print(f"Python list multiplication: {py_list * 2}")

np_array = np.array([1, 2, 3, 4, 5])    # it multiplies the values inside (basically element wise) 
print(f"Python list multiplication: {np_array * 2}")

import time

start = time.time()

py_list = [i*2 for i in range(1000000)]
print(f"\nTime for list multiplication: {(time.time() - start):.5f}")

start = time.time()

np_array = np.arange(1000000) * 2
print(f"Time for numpy arrat multiplication: {(time.time() - start):.5f}")

Python list multiplication: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Python list multiplication: [ 2  4  6  8 10]

Time for list multiplication: 0.27610
Time for numpy arrat multiplication: 0.00656


### Creating Numpy arrays from scratch
We have some methods provided by numpy to create arrays/matrices

- **np.zeros( (rows, column) ):** this gives array of zeros
- **np.ones( (rows, column) ):** this gives array of ones
- **np.full( (rows, column), any num ):** this gives array of any number you provide in the arguements
- **np.random( (row, column) ):** gives array of random numbers
- **np.arange( (start, stop, step) ):** gives array of sequence
- **np.eye( dimension):** gives identity matrix
- **np.linespace(start, stop, num):** returns evenly spaced values between a start and stop value. The `num` argument defines how many values to generate.

In [4]:
zeros = np.zeros((3,4))
print(f"Zeros array (matrice): \n{zeros}")

ones = np.ones((3,4))
print(f"\nOnes array (matrice): \n{ones}")

full = np.full((3,3),8)
print(f"\nFULL array (matrice) of any given number: \n{full}")

random = np.random.random((4,3))
print(f"\nArray (matrice) of random numbers: \n{random}")

sequence = np.arange(0, 11, 2)
print(f"\nSequence array: \n{sequence}")

eye = np.eye(5)
print(f"\nIdentity matrix: \n{eye}")

linespace = np.linspace(0, 15, 7)
print(f"\nArray with equally spaced values: {linespace}")

Zeros array (matrice): 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array (matrice): 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

FULL array (matrice) of any given number: 
[[8 8 8]
 [8 8 8]
 [8 8 8]]

Array (matrice) of random numbers: 
[[0.68119066 0.07176115 0.09879266]
 [0.58619133 0.69620531 0.65831427]
 [0.76484571 0.41342272 0.88732109]
 [0.08548184 0.50543966 0.56344407]]

Sequence array: 
[ 0  2  4  6  8 10]

Identity matrix: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Array with equally spaced values: [ 0.   2.5  5.   7.5 10.  12.5 15. ]


### Vector, Matrix and Tensor

- Vector is 1D array
- Matrix is 2D array
- Tensor is 3D array or more

In [8]:
vector = np.array([1, 2, 3])
print(f"Vector: \n{vector}")

matrix = np.array([ [1, 2, 3],
                    [4, 5, 6] ])
print(f"\nMatrix: \n{matrix}")

tensor = np.array([ [ [1, 2, 3], [4, 5, 6] ],
                   [ [7, 8, 9], [10, 11, 12] ] ])
print(f"\nTensor: \n{tensor}")

Vector: 
[1 2 3]

Matrix: 
[[1 2 3]
 [4 5 6]]

Tensor: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Numpy array properties

- **shape:** gives the shape of array, like whether its 2x3 or 4x5 etc.
- **ndim:** gives the dimension (1D, 2D, 3D.....)
- **size:** gives the number of elements present in the array.
- **dtype:** gives the datatype used in the array.

In [6]:
arr = np.array([ [1, 2, 3],
                 [4, 5, 6] ])

print(f"Shape: {arr.shape}")
print(f"Dimension: {arr.ndim}")
print(f"Size: {arr.size}")
print(f"Datatype: {arr.dtype}")

Shape: (2, 3)
Dimension: 2
Size: 6
Datatype: int32


### Manipulating the array

- **reshape**: will change the dimension of the array.
- **flatten**: will flatten the whole array into 1D. It returns a **copy** of the original array.
- **ravel**: works the same as flatten but returns a **view** (original array) if possible, so it's more memory efficient.
- **T**: will return the **transpose** of the array (rows become columns and columns become rows), e.g., 3x4 → 4x3.
- **resize**: modifies the original array in-place. If the new shape requires more elements, it repeats existing values or fills with 0s.


In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
print(f"Original array: {arr}")

reshaped = arr.reshape((3,4))   # will return an error if the reshape dimensions are not equal to the elements in the array
print(f"\nReshaped array: {reshaped}")

flattened = reshaped.flatten()
print(f"\nFlattened array: {flattened}")

raveled = reshaped.ravel()   #raveled is same function as flatten, but ravel returns the original array while flatten returns copy
print(f"\nRaveled array: {raveled}")

transpose = reshaped.T
print(f"\nTranspose: {transpose}")


# =========================================================
# Resize in 2 ways:

resized = np.resize(arr, (5,4))
print(f"\nResized: {resized}")

arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr2.resize(4,3)
print(f"\nResized: {arr2}")

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Resized: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]]

Resized: [[1 2 3]
 [4 5 6]
 [7 8 0]
 [0 0 0]]
