## Some more concepts in Numpy
---

### Insert

Inserting any element on any index in an array.

`Insert` function is not same as `hstack` and `vstack` because `insert` allows you to enter data at any index whereas `hstack` and `vstack` only adds rows and columns at the end.

`Syntax:` np.array(array_name, index, value, axis)

- **array_name:** The array in which data needs to be inserted.
- **index:** The index where data will be inserted.
- **value:** The value to be inserted.
- **axis (0 or 1):** The axis to target rows and column. (used in 2D array)

**`Note:`** In 1D array, you insert element, and in 2D array, you insert a row or a column.

In [ ]:
import numpy as np

# insertion in 1D array

arr = np.array([10, 20, 30, 40, 50, 60, 70])

print(f"Original Array: {arr}")

inserted_1d = np.insert(arr, 5, 100)

print(f"\nAfter inserting element at index 5: {inserted_1d}")

# -------------------------------------------------------

# insertion in 2D array

arr_2 = np.array([ [1, 2, 3, 4], [4, 5, 6, 7] ])

print(f"\n Original 2D array: \n{arr_2}")

inserted_2d_row = np.insert(arr_2, 1, [100, 200, 300, 400], axis=0)     # axis= 0 (inserting a row)

print(f"\n After inserting row in 2D array: \n{inserted_2d_row}")

inserted_2d_col = np.insert(arr_2, 1, [500, 600], axis=1)     # axis= 1 (inserting a col)

print(f"\n After inserting row in 2D array: \n{inserted_2d_col}")

Original Array: [10 20 30 40 50 60 70]

After inserting element at index 5: [ 10  20  30  40  50 100  60  70]

 Original 2D array: 
[[1 2 3 4]
 [4 5 6 7]]

 After inserting row in 2D array: 
[[  1   2   3   4]
 [100 200 300 400]
 [  4   5   6   7]]

 After inserting row in 2D array: 
[[  1 500   2   3   4]
 [  4 600   5   6   7]]


### Split

Splits a single array to multiple arrays. Provides 3 functions:

- **np.split()** Splits the array in equal parts.
- **np.hsplit()** Splits the array horizontally (column-wise)
- **np.vsplit()** Splits the array vertically (row-wise)

In [19]:
sample = np.array([1, 2, 3, 4, 5, 6])

print(f"Original Array: {sample}")

split = np.split(sample, 3)

print(f"\nEqually splitted array: \n{split}")

Original Array: [1 2 3 4 5 6]

Equally splitted array: 
[array([1, 2]), array([3, 4]), array([5, 6])]
