## Numpy Array Operations

### Indexing and Slicing

In [1]:
import numpy as np

- **Indexing and Slicing 1D Array**

In [10]:
arr = np.arange(1,11)
print(f"Orignal Array: {arr}")

print(f"\nIndexing any number: {arr[5]}")

print(f"\nNegative indexing: {arr[-3]}")

print(f"\nSlicing: {arr[3:6]}")

print(f"\nSlicing with step: {arr[1:9:2]}")

print(f"\nNegative Slicing: {arr[-5:-2]}")

Orignal Array: [ 1  2  3  4  5  6  7  8  9 10]

Indexing any number: 6

Negative indexing: 8

Slicing: [4 5 6]

Slicing with step: [2 4 6 8]

Negative Slicing: [6 7 8]


- **Indexing and Slicing 2D Array**

In [19]:
arr_2D = np.array([ [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9] ])

print(f"Original 2D Array:\n{arr_2D}")

# targeting an element on specific row and column
print(f"\nSpecific element: {arr_2D[2,2]}")         # 3rd row 3rd column

# targeting entire row
print(f"\nEntire row: {arr_2D[1]}")                 # entire 2nd row

# targeting entire column
print(f"\nEntire column: {arr_2D[:,0]}")            # entire 1st column

Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Specific element: 9

Entire row: [4 5 6]

Entire column: [1 4 7]


### Sorting arrays

In [ ]:
arr_1D_unsorted = np.array([3, 5, 2, 5, 1, 8, 0, 4, 2, 9, 6])
print(f"Unsorted 1D array: {arr_1D_unsorted}")

print(f"\nSorted 1D array: {np.sort(arr_1D_unsorted)}")

arr_2D_unsorted = np.array([ [3, 1],
                             [1, 2],
                             [2, 3] ])

print(f"\nUnsorted 2D array: \n{arr_2D_unsorted}")

print(f"\nSorted 2D array by column: \n{np.sort(arr_2D_unsorted, axis=0)}") # axis = 0 for column-wise sorting
print(f"\nSorted 2D array by row: \n{np.sort(arr_2D_unsorted, axis=1)}")    # axis = 0 for row-wise sorting

Unsorted 1D array: [3 5 2 5 1 8 0 4 2 9 6]

Sorted 1D array: [0 1 2 2 3 4 5 5 6 8 9]

Unsorted 2D array: 
[[3 1]
 [1 2]
 [2 3]]

Sorted 2D array by column: 
[[1 1]
 [2 2]
 [3 3]]

Sorted 2D array by row: 
[[1 3]
 [1 2]
 [2 3]]
