## Some more concepts in Numpy
---

### Insert

Inserting any element on any index in an array.

`Insert` function is not same as `hstack` and `vstack` because `insert` allows you to enter data at any index whereas `hstack` and `vstack` only adds rows and columns at the end.

`Syntax:` np.array(array_name, index, value, axis)

- **array_name:** The array in which data needs to be inserted.
- **index:** The index where data will be inserted.
- **value:** The value to be inserted.
- **axis (0 or 1):** The axis to target rows and column. (used in 2D array)

**`Note:`** In 1D array, you insert element, and in 2D array, you insert a row or a column.

In [ ]:
import numpy as np

# insertion in 1D array

arr = np.array([10, 20, 30, 40, 50, 60, 70])

print(f"Original Array: {arr}")

inserted_1d = np.insert(arr, 5, 100)

print(f"\nAfter inserting element at index 5: {inserted_1d}")

# -------------------------------------------------------

# insertion in 2D array

arr_2 = np.array([ [1, 2, 3, 4], [4, 5, 6, 7] ])

print(f"\n Original 2D array: \n{arr_2}")

inserted_2d_row = np.insert(arr_2, 1, [100, 200, 300, 400], axis=0)     # axis= 0 (inserting a row)

print(f"\n After inserting row in 2D array: \n{inserted_2d_row}")

inserted_2d_col = np.insert(arr_2, 1, [500, 600], axis=1)     # axis= 1 (inserting a col)

print(f"\n After inserting row in 2D array: \n{inserted_2d_col}")

Original Array: [10 20 30 40 50 60 70]

After inserting element at index 5: [ 10  20  30  40  50 100  60  70]

 Original 2D array: 
[[1 2 3 4]
 [4 5 6 7]]

 After inserting row in 2D array: 
[[  1   2   3   4]
 [100 200 300 400]
 [  4   5   6   7]]

 After inserting row in 2D array: 
[[  1 500   2   3   4]
 [  4 600   5   6   7]]


### Split

Splits a single array to multiple arrays. Provides 3 functions:

- **np.split()** Splits the array in equal parts.
- **np.hsplit()** Splits the array horizontally (column-wise)
- **np.vsplit()** Splits the array vertically (row-wise)

In [ ]:
# 1d split:

sample = np.array([1, 2, 3, 4, 5, 6])

print(f"Original Array: {sample}")

split = np.split(sample, 3)

print(f"\nEqually splitted array: \n{split}")

Original Array: [1 2 3 4 5 6]

Equally splitted array: 
[array([1, 2]), array([3, 4]), array([5, 6])]


In [29]:
# 2D Split:

sample_2d = np.array([ [1, 2, 4, 5], [7, 8, 9, 4], [3, 4, 5, 0], [4, 4, 4, 1] ])

print(f"Original Array: {sample_2d}")

split_2d = np.split(sample_2d, 2)

print(f"\nEqually splitted 2D array: \n{split_2d}")

Original Array: [[1 2 4 5]
 [7 8 9 4]
 [3 4 5 0]
 [4 4 4 1]]

Equally splitted 2D array: 
[array([[1, 2, 4, 5],
       [7, 8, 9, 4]]), array([[3, 4, 5, 0],
       [4, 4, 4, 1]])]


In [31]:
# hsplit:

print(f"Original Array: \n{sample_2d}")

hsplit = np.hsplit(sample_2d, 2)

print(f"\nHorizontally splitted 2D array: \n{hsplit}")

Original Array: 
[[1 2 4 5]
 [7 8 9 4]
 [3 4 5 0]
 [4 4 4 1]]

Horizontally splitted 2D array: 
[array([[1, 2],
       [7, 8],
       [3, 4],
       [4, 4]]), array([[4, 5],
       [9, 4],
       [5, 0],
       [4, 1]])]


In [32]:
# vsplit:

print(f"Original Array: \n{sample_2d}")

vsplit = np.vsplit(sample_2d, 2)

print(f"\nHorizontally splitted 2D array: \n{vsplit}")

Original Array: 
[[1 2 4 5]
 [7 8 9 4]
 [3 4 5 0]
 [4 4 4 1]]

Horizontally splitted 2D array: 
[array([[1, 2, 4, 5],
       [7, 8, 9, 4]]), array([[3, 4, 5, 0],
       [4, 4, 4, 1]])]


### isnan function

Checks whether there is any NaN value inside of an array. 
Returns a boolean value

In [39]:
nan_array = np.array([10, 24, np.nan, 50, np.nan, 100])

print(f"Original Array: {nan_array}")

print(f"\nChecking any NaN values: {np.isnan(nan_array)}")

Original Array: [ 10.  24.  nan  50.  nan 100.]

Checking any NaN values: [False False  True False  True False]


### nan_to_num function

Replaces all the NaN values with a specified value given in the array.

By default, it replaces with 0 if any value is not specified.

In [40]:
print(f"Original Array: {nan_array}")

print(f"\nNaN replaced with default 0: {np.nan_to_num(nan_array)}")

print(f"\nNaN replaced with specified value: {np.nan_to_num(nan_array, nan=15)}")

Original Array: [ 10.  24.  nan  50.  nan 100.]

NaN replaced with default 0: [ 10.  24.   0.  50.   0. 100.]

NaN replaced with specified value: [ 10.  24.  15.  50.  15. 100.]


### isinf function

- Checks whether there is any infinite value inside of an array or not.


- Returns a boolean array with the result.


- Infinite values can either be positive or negative.

In [42]:
inf_array = np.array([10, 29, np.inf, 94, 399, -np.inf, 43, np.inf])

print(f"Original Array: {inf_array}")

print(f"\n Checking any infinite values: {np.isinf(inf_array)}")

Original Array: [ 10.  29.  inf  94. 399. -inf  43.  inf]

 Checking any infinite values: [False False  True False False  True False  True]


### nan_to_num function (to replace infinite values)

- Replaces the infinity values with the given values.


- We can give seperate values to replace for `positive infinity` and `negative infinity`.

In [43]:
print(f"Original Array: {inf_array}")

print(f"\n Infinity values replaced with specified values: {np.nan_to_num(inf_array, posinf=100, neginf=-100)}")

Original Array: [ 10.  29.  inf  94. 399. -inf  43.  inf]

 Infinity values replaced with specified values: [  10.   29.  100.   94.  399. -100.   43.  100.]
